wedish/wedish/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('wedish_site/', include('wedish_site.urls')),
    path('', RedirectView.as_view(url='wedish_site/', permanent=True)),

)

wedish/wedish_site/urls.py
from django.urls import path
from . import views

app_name = 'wedish_site'
urlpatterns = [
    path('', views.index, name='index'),
    
]

wedish/wedish_accounting/models.py
from django.conf import settings
from datetime import date
from django.db import models
from django.utils.translation import gettext_lazy as _


class Order(models.Model):
    quantity = models.CharField(_('Quantity'), max_length=100, db_index=True)
    price = models.CharField(_('Price'), max_length=100, db_index=True)
    completed_at = models.DateTimeField(_('completed_at'), null=True, blank=True, db_index=True)
    table_number = models.CharField(_('Table number'), max_length=100, db_index=True)
    #dish = fk?
    #drinks = fk?

    def __str__(self) -> str:
        return self.price

class Bill(models.Model):
    # payment = fk?
    customer = models.CharField(_('Customer'))#??
    total_price = models.IntegerField(_('Total price'), db_index=True)
    # order = fk?

class VAT(models.Model):
    #country
    rate = models.DecimalField(_('Rate'), max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    start_date = models.DateTimeField(_('Start date'), auto_now_add=True)
    
    def __str__(self):
        return f'{self.rate} {self.start_date}'

class Payment(models.Model):
    payment_method = models.CharField(_('Payment method'), max_length=100, db_index=True)
    currency = models.CharField(_('Currency'), max_length=10, db_index=True)

wedish/wedish_site/models.py
from django.db import models
from treebeard.mp_tree import MP_Node



# Create your models here.


class Category(MP_Node):
    name = models.CharField(max_length=100)
    node_order_by = ['name']

    def __str__(self):
        return 'Category: {}'.format(self.name)


data = [{'data':{'name':'Category'}, 'children':[
            {'data':{'name':'Product'}, 'children':[
                {'data':{'name':'Meal'}, 'children':[
                    {'data':{'name':'Breakfast'}},
                    {'data':{'name':'Brunch'}},
                    {'data':{'name':'Lunch'}},
                    {'data':{'name':'Hi-Tea'}},
                    {'data':{'name':'Dinner'}},
                    {'data':{'name':'Supper'}},
                    ]},
                {'data':{'name':'Drink'}, 'children':[
                    {'data':{'name':'Soft drinks'}},
                    {'data':{'name':'Coctail'}},
                    {'data':{'name':'Alcohol'}},
                    {'data':{'name':'Alcohol coktail'}},
                    {'data':{'name':'Tea'}},
                    {'data':{'name':'Coffee'}},
                    ]},
                {'data':{'name':'Other'}},
                ]},
            {'data':{'name':'Service'}, 'children':[
                {'data':{'name':'Place to eat'}},
                {'data':{'name':'Take out'}},
                ]},
            {'data':{'name':'General_Product'}, 'children':[
                {'data':{'name':'Grains'}},
                {'data':{'name':'Vegetable'}},
                {'data':{'name':'Fruits'}},
                {'data':{'name':'Meat'}},
                {'data':{'name':'Liquids'}},
                {'data':{'name':'Spices'}},
                {'data':{'name':'Eggs, milk...'}},
                 ]},
            {'data':{'name':'Brand'}},
            {'data':{'name':'Unit'},  'children':[
                {'data':{'name':'Weight'}},
                {'data':{'name':'Temperature'}},
                {'data':{'name':'Data'}},
                {'data':{'name':'Time'}},
                {'data':{'name':'Lenght'}},
                {'data':{'name':'Currency'}},
                ]}, 
            ]},
]

wedish/wedish_store/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)


class GenericProduct(models.Model):
    name = models.CharField(max_length=100)
    #allergen foreign key? example: nuts , eggs, milk, wheat, soy, seafood
    #type foreign key? example: vegan, vegetarian, meat, dairy, glutenfree...


class Service(models.Model):
    name = models.CharField(max_length=100)


class Unit(models.Model):
    name = models.CharField(max_length=100)
    # Type of Measurement: temperature, volume, weight


class Brand(models.Model):
    name = models.CharField(max_length=100)
    

wedish/wedish_accounting/views.py
from django.shortcuts import render

# Create your views here.

wedish/wedish_site/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'wedish_site/index.html')

wedish/wedish_site/templates/wedish_site/base.html
<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load i18n %}
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'service/css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <title>{% block title %}{% trans 'Car Service' %}{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% block navigation %}
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'wedish_site:index' %}">{% trans 'Home' %}</a></li>
            {% if request.user.is_superuser or request.user.is_staff %}
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
            {% endif %}
        </ul>
        {% endblock navigation %}
        </div>
    </nav>
    <div class="container">
        {% block messages %}
            {% if messages %}
                {% for message in messages%}
                    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endblock messages %}

        {% block content %}{% endblock content %}
        {% if debug %}{% block debug %}
        <div class="debug">{{ debug }}</div>
        {% endblock debug %}{% endif %}
    </div>        
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

wedish/wedish_site/templates/wedish_site/index.html
{% extends 'wedish_site/base.html' %}
{% load i18n %}

{% block content %}

<h1>Hello world</h1>

{% endblock content %}